# Generated by Django 3.1.7 on 2021-03-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisorId', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('teamId', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('numberOfTeamMembers', models.IntegerField()),
                ('topic', models.CharField(max_length=50)),
                ('advisorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainForm.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationLog',
            fields=[
                ('teamId', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainForm.teaminformation', verbose_name='TeamID')),
                ('requirementsPresentation_Date', models.DateField(null=True)),
                ('requirementsPresentation_Completed', models.BooleanField(default=False)),
                ('designPresentation_Date', models.DateField(null=True)),
                ('designPresentation_Completed', models.BooleanField(default=False)),
                ('FinalPresentation_Date', models.DateField(null=True)),
                ('FinalPresentation_Completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('eid', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='@ksu.edu', max_length=60)),
                ('is_admin', models.BooleanField(default=False)),
                ('teamID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainForm.teaminformation')),
            ],
        ),
    ]
