# Generated by Django 3.1.7 on 2021-04-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='teaminformation',
            name='teamId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
